// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RivieraSecrete.Infrastructure.Data;

#nullable disable

namespace RivieraSecrete.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RivieraSecrete.Domain.Entities.Activite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActiviteId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Alt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Badge")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Duree")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LieuId")
                        .HasColumnType("integer");

                    b.Property<string>("LinkText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prix")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LieuId");

                    b.ToTable("Activites");
                });

            modelBuilder.Entity("RivieraSecrete.Domain.Entities.Itineraire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Badge")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Booking")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HeroImgTag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Intro")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Items")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("MapLabel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MetaPills")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Suggestions")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Itineraires");
                });

            modelBuilder.Entity("RivieraSecrete.Domain.Entities.Lieu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Badges")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Commune")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description2")
                        .HasColumnType("text");

                    b.Property<string>("HeroAlt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HeroImage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("HeroSlides")
                        .HasColumnType("integer");

                    b.Property<double>("Lat")
                        .HasColumnType("double precision");

                    b.Property<double>("Lng")
                        .HasColumnType("double precision");

                    b.Property<string>("MetaPills")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("OgImage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RegionLabel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RegionSlug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Related")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ThumbImage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tips")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("VilleSlug")
                        .IsRequired()
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("VilleSlug");

                    b.ToTable("Lieux");
                });

            modelBuilder.Entity("RivieraSecrete.Domain.Entities.Ville", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Lat")
                        .HasColumnType("double precision");

                    b.Property<double>("Lng")
                        .HasColumnType("double precision");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RegionLabel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RegionSlug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ThumbImage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Villes");
                });

            modelBuilder.Entity("RivieraSecrete.Domain.Entities.Activite", b =>
                {
                    b.HasOne("RivieraSecrete.Domain.Entities.Lieu", "Lieu")
                        .WithMany("Activites")
                        .HasForeignKey("LieuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lieu");
                });

            modelBuilder.Entity("RivieraSecrete.Domain.Entities.Lieu", b =>
                {
                    b.HasOne("RivieraSecrete.Domain.Entities.Ville", "Ville")
                        .WithMany("Lieux")
                        .HasForeignKey("VilleSlug")
                        .HasPrincipalKey("Slug")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ville");
                });

            modelBuilder.Entity("RivieraSecrete.Domain.Entities.Lieu", b =>
                {
                    b.Navigation("Activites");
                });

            modelBuilder.Entity("RivieraSecrete.Domain.Entities.Ville", b =>
                {
                    b.Navigation("Lieux");
                });
#pragma warning restore 612, 618
        }
    }
}
